#!/bin/sh

session=${1:-i3}

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

case $session in
	i3 )
		exec i3
		;;
	xmonad )
		exec xmonad
		;;
	xfce )
		exec startxfce4
		;;
	gnome )
		export XDG_SESSION_TYPE=x11
		export GDK_BACKEND=x11
		exec gnome-session
		;;
	# No known session, try to run it as command
	* )
		exec $1
		;;
esac
