### Start of Zplug's installer
if [[ ! -f $HOME/.zplug/init.zsh ]]; then
    print -P "Installing zplug..."
    git clone https://github.com/zplug/zplug $HOME/.zplug
fi

source "$HOME/.zplug/init.zsh"

### Enables autocompletion
autoload -Uz compinit 
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
    compinit;
else
    compinit -C;
fi;

zstyle ":completion:*" menu select
setopt COMPLETE_ALIASES
zstyle ":completion::complete:*" gain-privileges 1

### Plugins
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/git-auto-fetch", from:oh-my-zsh
zplug "plugins/git-prompt", from:oh-my-zsh

### Theme
zplug "romkatv/powerlevel10k", as:theme, depth:1

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
    echo
fi

zplug load

### Variables
# Sets history file
HISTFILE=$HOME/.zsh_history
# Sets maximum history file size
HISTSIZE=10000
# Sets current session commands to be saved to file
SAVEHIST=1000
# Appends into history file
setopt INC_APPEND_HISTORY
# Saves only one command if duplicates are found
setopt HIST_IGNORE_DUPS
# Adds a timestamp for each entry
setopt EXTENDED_HISTORY

### Custom binds
bindkey "^[[3~"   delete-char        #DELETE
bindkey "^[[H"    beginning-of-line  #HOME
bindkey "^[[F"    end-of-line        #END
bindkey "^[[4~"   end-of-line        #END (st)
bindkey "^[[1;5C" forward-word       #CTRL + RIGHT ARROW
bindkey "^[[1;5D" backward-word      #CTRL + LEFT ARROW
bindkey "^H"      backward-kill-word #CTRL + BACKSPACE
bindkey "^[[3;5~" kill-word          #CTRL + DELETE

### Custom aliases
alias ll="ls -l"
alias rm="trash"
alias enw="emacs -nw"
alias storage="cd /mnt/storage"

### Set wallpaper script
function wal-tile() {
  cached_path="${HOME}/.cache/wal/wallpaper_file"

  wal -ns -i "$@"

  cp -f "$@" ${cached_path}
  swww img ${cached_path}
}

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(zoxide init zsh)"
